### ISSUE TITLE
How to convert audio to features of `438` dims

### ISSUE THREAD

**Issue by Zessay** [openxrlab/xrmogen#8]
Thanks for your code, I just wonder how to convert each frame of origin audio to features of `438` dims. Look forward to your reply, thanks again.

**Comment by lisiyao21** [comment]
Thank you for your support on our work! 

The original audio is transformed to features via libarosa toolbox. It can be refered to https://github.com/lisiyao21/Bailando/blob/a2690496883cd41fb9782203ab328dae146100c7/_prepro_aistpp_music.py#L92

**Comment by Zessay** [comment]
> Thank you for your support on our work!
> 
> The original audio is transformed to features via libarosa toolbox. It can be refered to https://github.com/lisiyao21/Bailando/blob/a2690496883cd41fb9782203ab328dae146100c7/_prepro_aistpp_music.py#L92

Thanks for your reply! 😃
